/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2a9f8226-357f-4eee-8e3d-2aa49fe2bbeb",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_mNtxAnvjD",
    "aws_user_pools_web_client_id": "5u6seokrk1pjtovghhop6i3trl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k6q5mgbrargpnfao423orq4fce.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

console.log('aws-exp')

export default awsmobile;
